# Build a Docker image for main branch PRs. Thereby also run pytest to verify the
# image builds correctly. This workflow is similar to push-stable-docker-image.yml,
# but does not push the image to Docker Hub. It also runs only on pull requests to main,
# whereas push-stable-docker-image.yml runs on pushes (PRs accepted) to main.
#
# NOTE: For now, this workflow does not run as intended, since it will run on the branch
# defined by the stable Dockerfile, which is main. What is needed is to reconfigure
# the dockerfile and GH workflow to build from the PR branch instead. This should be
# revisited later.
name: Build a Docker image for main branch PRs

on:
  workflow_dispatch:
    # run jobs manually
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push stable
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./dockerfiles/stable/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/stable:latest

